export const userSafeSelect = {
  id: true,
  publicUuid: true,
  email: true,
  fullName: true,
  displayName: true,
  avatarUrl: true,
  role: true,
  status: true,
  country: true,
  timezone: true,
  declaredLevel: true,
  softwareStack: true,
  availabilityText: true,
  workloadScore: true,
  acceptedOffersCount: true,
  totalOffersCount: true,
  acceptanceRate: true,
  lastLoginAt: true,
  createdAt: true,
  updatedAt: true,
} as const;
